TRAIN:
  ENABLE: True
  EPOCHES: 10
  DROPOUT: False
  DROPOUT_RATE: 0.5
  VAL: True # 每次是否进行validation
TEST:
  ENABLE: False
MODEL:
  NAME: "MLP" # MLP, LINEAR, SOFTMAX
  INNER_DIM: 32
  LAYER_NUM: 3
  INPUT_DIM: 784
  NUM_CLASSES: 10
DATASETS:
  NAME: "FASIONMNIST" # FASHIONMNIST MNIST CIFAR10 CIFAR100
BS: 128
NUM_WORKERS: 4
LR: 0.1
OPTIMIZER: SGD # SGD, ADAM
VISUAL: False