TRAIN:
  ENABLE: True
  EPOCHES: 20
  DROPOUT: False
  DROPOUT_RATE: 0.5
  VAL: True # 每次是否进行validation
TEST:
  ENABLE: False
MODEL:
  NAME: "RESNET18" # LENET, MLP, LINEAR, SOFTMAX, RESNET18, RESNET32, RESNET50, RESNET101
  INNER_DIM: 32
  LAYER_NUM: 3
  INPUT_DIM: 784
  NUM_CLASSES: 10
DATASETS:
  NAME: "CIFAR10" # FASHIONMNIST MNIST CIFAR10 CIFAR100
BS: 64
NUM_WORKERS: 4
LR: 0.1
OPTIMIZER: SGD # SGD, ADAM
VISUAL: False